import turtle

screen = turtle.Screen()
screen.bgcolor('lightpink')

t=turtle.Turtle()
t.speed(0)
t.penup()
t.goto(0,200)
t.pendown()
t.write("All About Me", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Naima Juma", font=("Arial", 35, "bold"), align="center")
t.penup()
#circle
t.penup()
t.begin_fill()
t.goto(-200,200)
t.pendown()
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.fillcolor('Aliceblue')
t.end_fill()
#circle
t.penup()
t.begin_fill()
t.goto(200,200)
t.pendown()
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.fillcolor('Aliceblue')
t.end_fill()


#circle
t.penup()
t.begin_fill()
t.goto(200,-200)
t.pendown()
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.fillcolor('Aliceblue')
t.end_fill()


#circle
t.penup()
t.begin_fill()
t.goto(-200,-200)
t.pendown()
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.left(90)
t.circle(25)
t.fillcolor('Aliceblue')
t.end_fill()



t2=turtle.Turtle()
t2.penup()
turtle.addshape("night.gif")
t2.shape("night.gif")
t2.goto(100,100)
a=t2.stamp()

t2.penup()
turtle.addshape("dark.gif")
t2.shape("dark.gif")
t2.goto(-100,100)
a=t2.stamp()
enter=input("Press Enter to Start")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('orange')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Foods", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(-160,40)
t.write("burgers", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(0,40)
t.write("hot dogs", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(240,40)
t.write("chicken alfredo", font=("Arial", 20, "bold"), align="center")
t.penup()
t.goto(-75, 105)
t.fillcolor('purple')
t.pendown()
t.begin_fill()
t.forward(150)
t.left(90)
t.forward(100)
t.left(90)
t.forward(150)
t.left(90)
t.forward(100)
t.end_fill()

t2.penup()
turtle.addshape("burger.gif")
t2.shape("burger.gif")
t2.goto(100,-100)
a=t2.stamp()

t2.penup()
t2.goto(-100,-100)
turtle.addshape("hot dogs.gif")
t2.shape("hot dogs.gif")
t2.goto(-100,-100)
a=t2.stamp()
t2.goto(-100,-200)

t2.penup()
t2.goto(-100,100)
turtle.addshape("alfredo.gif")
t2.shape("alfredo.gif")
t2.goto(-100,100)
a=t2.stamp()
t2.goto(-100,200)



enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('powder blue')
t.pencolor('black')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Hobbies", font=("Arial", 35, "bold"), align="center")
t.penup()
t.penup()
t.goto(-250,40)
t.write("reading", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(-150,40)
t.write("movies", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(-40,40)
t.write("cooking", font=("Arial", 15, "bold"), align="center")
t.penup()
t.goto(140,40)
t.write("working out", font=("Arial", 15, "bold"), align="center")
t.penup()
t.pencolor('black')
t.fillcolor('pink')
t.begin_fill()
t.goto(-50,-10)
t.pendown()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.end_fill()
t2.penup()
turtle.addshape("books.gif")
t2.shape("books.gif")
t2.goto(100,-200)
a=t2.stamp()


t2.penup()
turtle.addshape("netflix.gif")
t2.shape("netflix.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)

t2.penup()
turtle.addshape("cooking.gif")
t2.shape("cooking.gif")
t2.goto(100,200)
a=t2.stamp()
t2.goto(100,200)

t2.penup()
turtle.addshape("workingout.gif")
t2.shape("workingout.gif")
t2.goto(-100,200)
a=t2.stamp()
t2.goto(-100,200)

enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('medium slate blue')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Movie", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(-10,100)
t.pencolor('green')
t.fillcolor('green')
t.penup()
t.goto(-10,100)
t.pencolor('blue')
t.fillcolor('orange')
t.pendown()
t.begin_fill()
t.circle(30,180)
t.end_fill()
t.penup()
t.goto(0,-50)
t.pendown()
t.pencolor("black")
t.write("20th century girl", font=("Arial", 35, "bold"), align="center")

t2.penup()
turtle.addshape("20 century girl.gif")
t2.shape("20 century girl.gif")
t2.goto(100,-200)
a=t2.stamp()


t2.penup()
turtle.addshape("20 century girl.gif")
t2.shape("20 century girl.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)
enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('pale green')
t.penup()
t.goto(0,200)
t.pendown()
t.write("My Favorite Sport", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Track", font=("Arial", 35, "bold"), align="center")
t.penup()
t.goto(60,10)
t.fillcolor('blue')
t.pendown()
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.end_fill()

t2.penup()
turtle.addshape("long jump.gif")
t2.shape("long jump.gif")
t2.goto(100,-200)
a=t2.stamp()


t2.penup()
turtle.addshape("track.gif")
t2.shape("track.gif")
t2.goto(-100,-200)
a=t2.stamp()
t2.goto(-100,-200)

enter=input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()


